name: Print

on:
  push:
    branches:
      - staging

jobs:
  print-hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Print hello world
        id: print_hello_world
        run: |
          echo "Hello world"